#!/bin/bash
#SBATCH -N 1
#SBATCH --tasks-per-node=28
#SBATCH --time=1:00:00
#SBATCH --error="%x.e%j"
#SBATCH --output="%x.o%j"
#SBATCH --job-name="H"
#SBATCH --mem=120G

module load OpenMPI/3.0.0-GCC-7.2.0-2.29 
module load apps/orca/4.2.0
 
export RSH_COMMAND="/usr/bin/ssh -x"

cd /mnt/storage/scratch/zw18965/MN/SRMBE13/B2PLYP-D3BJ

echo ${SLURM_NODELIST} > H.nodes

$(which orca) "H.in" &> "H.out"
